// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rphropgcttgyhwwouqqy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJwaHJvcGdjdHRneWh3d291cXF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2MTIxODAsImV4cCI6MjA3MDE4ODE4MH0.tKcgpCRlkfnf7sYsz2XAbaV54kMKDF5FYWxf-HFER0g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});